### ISSUE TITLE
Docker-Compose issue::Container Communication Failure [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by anasdeis** [anasdeis/Electronic-Monkey#10]
In GitLab by @Somsubhra on Aug 24, 2021, 16:24

Hi,

Please note that I have modified the Dockerfile for UserService which was creating the problem due to not having all the content of the UserService module which led to build failure:

```
FROM openjdk:11-jre-slim
WORKDIR usr/src
ADD ./target/userservice-1.0.0.jar /usr/src/userservice-1.0.0.jar
ENTRYPOINT ["java","-jar","userservice-1.0.0.jar"]
```

Please ensure that you build the application(not the UserService only as there is a parent-child relationship between root pom and pom of UserService) by running `mvn clean install -DskipTests`. This will build the application regardless of whether the test cases pass.

Also, there was an error regarding DB name. In the `application.properties` file, you have provided the name of the database to be `userDB`. However, in the `docker-compose.yml` file, the default database name was mentioned as testDB, hence the correct database was not getting created and an error was showing up. 

```yml
  db:
    container_name: db
    image: mysql:8.0
    #ports:
     # - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: userDB
      MYSQL_ROOT_PASSWORD: password
```

Making these modifications should fix the issue.
