### ISSUE TITLE
Containerization Issue::UserService Unable to Communicate with MySQL

### ISSUE THREAD

**Issue by anasdeis** [anasdeis/Electronic-Monkey#24]
In GitLab by @Somsubhra on Sep 3, 2021, 09:12

Hi,

Please find the updated docker-compose.yml file:

```yaml
# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.5'

# Define services
services:
  # App backend service
  userservice:
    # Configuration for building the docker image for the backend service
    build:
      context: userservice # Use an image built from the specified dockerfile in the `userservice` directory.
      dockerfile: Dockerfile
    ports:
      - "8090:8090" # Forward the exposed port 8080 on the container to port 8090 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.

  # Frontend Service
  # webapp:
  #   build:
  #     context: webApp # Use an image built from the specified dockerfile in the `webApp` directory.
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:80" # Map the exposed port 80 on the container to port 8081 on the host machine
  #   restart: always
  #   depends_on:
  #     - userservice

  # Database Service (Mysql)
  db:
    container_name: db
    image: mysql:8.0
    # ports:
    #  - "3308:3306"
    restart: always
    environment:
      MYSQL_DATABASE: userDB
      MYSQL_ROOT_PASSWORD: password

```

Please note:
- The UserService Microservice is communicating with the MySQL Container via an internal network using docker-compose. Hence, there is no need to expose the port.
- Please check your frontend. I can see there is issue with containerizing the front end.
- change the docker-compose version to `3.5`
